services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"  

    depends_on:
      - sqlserver

    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ClipSnipDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=true"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  